### ISSUE TITLE
Multiple return!

### ISSUE THREAD

**Issue by bitsnaps** [CorpoSense/Smartboard_test#1]
https://github.com/CorpoSense/Smartboard_test/blob/ae983bcc9206cd2a94ec32aa4740763da2d23226/application/routes.py#L87

**Comment by meriem-batata** [comment]
we deleted it but apparently once we did `git pull` it came back , it's an error anyway

**Comment by bitsnaps** [comment]
Close [6db846c](https://github.com/CorpoSense/Smartboard_test/commit/6db846c51b713b52760ca59035e5b9981415cfae)
